### ISSUE TITLE
switch to the new vis-network module

### ISSUE THREAD

**Issue by mojoaxel** [Vincent-CIRCL/visjs_classificator#1]
`almende/vis` is now maintained by the community: www.visjs.org
I would recommend switching to the official successor [vis-network](https://github.com/visjs/vis-network)

**Comment by Vincent-CIRCL** [comment]
Thanks a lot. It will. I was waiting for it to be refractored before modifying things on my side. Thanks !

**Comment by mojoaxel** [comment]
:tada: You're welcome!

**Comment by mojoaxel** [comment]
If you encounter any Problems please let us know: https://github.com/visjs/vis-network/issues
